### ISSUE TITLE
Drupal\twig_fractal\Node\Render::getEnvironment() return null

### ISSUE THREAD

**Issue by woldtwerk** [netzstrategen/drupal-twig_fractal#26]
Hi there,

I get the following Error:
`TypeError: Return value of Drupal\twig_fractal\Node\Render::getEnvironment() must be an instance of Twig\Environment, null returned in Drupal\twig_fractal\Node\Render::getEnvironment() (line 47 of modules/contrib/twig_fractal/src/Node/Render.php).`

in Line 70 of web/modules/contrib/twig_fractal/src/Node/Render.php
get Enviroment gets called:
`web/modules/contrib/twig_fractal/src/Node/Render.php`

This only return a twig enviroment after a drush cr. On the next pageload it returns null.

Any hints?
Thx alot.

**Comment by sun** [comment]
https://github.com/netzstrategen/twig_fractal/pull/31 should resolve this issue. Can you test?
