### ISSUE TITLE
Confusion between this and fractal-twig repo

### ISSUE THREAD

**Issue by adamrobinson** [netzstrategen/drupal-twig_fractal#28]
Hi.

Im trying to integrate fractal and drupal twig templates together and have come across this and another one of your repos https://github.com/netzstrategen/fractal-twig .

Im currently using @wearewondrous/fractal-twig-drupal-adapter and have that working (sort of) but as its not been updated in a while i wanted to try this out but im just confused with both these packages that seem to refer to each other and the installation steps needed.

So do i need to install both this and your other repo to have this working in a drupal project?

**Comment by sun** [comment]
https://github.com/netzstrategen/twig_fractal (this package) adds support for the `{% render %}` tag to the Twig environment in PHP (of your application).

https://github.com/netzstrategen/fractal-twig adds support for the `{% render %}` tag to the Twig environment in JavaScript (of the Fractal UI).
